export enum SubsAndPlansActionTypes {
    SUBSCRIPTION_PLAN_LIST = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_LIST',
    SUBSCRIPTION_PLAN_LIST_SUCCESS = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_LIST_SUCCESS',
    SUBSCRIPTION_PLAN_LIST_ERROR = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_LIST_ERROR',

    SUBSCRIPTION_PLAN_DELETE = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_DELETE',
    SUBSCRIPTION_PLAN_DELETE_SUCCESS = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_DELETE_SUCCESS',
    SUBSCRIPTION_PLAN_DELETE_ERROR = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_DELETE_ERROR',

    SUBSCRIPTION_PLAN_ADD = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_ADD',
    SUBSCRIPTION_PLAN_ADD_SUCCESS = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_ADD_SUCCESS',
    SUBSCRIPTION_PLAN_ADD_ERROR = '@@subscriptionsAndPlans/SUBSCRIPTION_PLAN_ADD_ERROR',

    SUBSCRIPTION_ADD = '@@subscriptionsAndPlans/SUBSCRIPTION_ADD',
    SUBSCRIPTION_ADD_SUCCESS = '@@subscriptionsAndPlans/SUBSCRIPTION_ADD_SUCCESS',
    SUBSCRIPTION_ADD_ERROR = '@@subscriptionsAndPlans/SUBSCRIPTION_ADD_ERROR',
}
